# =====================================================================
#  Dominio: tienda-acme.com (y sus subdominios)
#  Un solo certificado comodín cubre el dominio raíz + *.tienda-acme.com
# =====================================================================

server {
    listen 80;
    server_name tienda-acme.com www.tienda-acme.com
                rrhh.tienda-acme.com ventas.tienda-acme.com;

    return 301 https://$host$request_uri;
}

# --- HTTPS: rrhh.tienda-acme.com -> RRHH ---
server {
    listen 443 ssl;
    server_name rrhh.tienda-acme.com;

    ssl_certificate     /etc/nginx/certs/tienda-acme/tienda-acme.com+4.pem;
    ssl_certificate_key /etc/nginx/certs/tienda-acme/tienda-acme.com+4-key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $backend_rrhh module-rrhh:3000;
        proxy_pass http://$backend_rrhh;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# --- HTTPS: ventas.tienda-acme.com -> VENTAS ---
server {
    listen 443 ssl;
    server_name ventas.tienda-acme.com;

    ssl_certificate     /etc/nginx/certs/tienda-acme/tienda-acme.com+4.pem;
    ssl_certificate_key /etc/nginx/certs/tienda-acme/tienda-acme.com+4-key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $backend_ventas module-ventas:3000;
        proxy_pass http://$backend_ventas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
