services:
  nginx:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro          # todos los .conf en una carpeta
      - ./certificados:/etc/nginx/certs:ro   # certificados generados
    restart: unless-stopped
    networks:
      - tienda-acme-net
      - nurcito-net

networks:
  tienda-acme-net:
    external: true
  nurcito-net:
    external: true
