# ===== Virtual host: otra-empresa.com -> contenedor PORTAL =====
# Dominio raíz DISTINTO -> usa su PROPIO certificado (no el de tienda-acme)

# --- HTTP (puerto 80): redirige a HTTPS ---
server {
    listen 80;
    server_name otra-empresa.com www.otra-empresa.com;

    return 301 https://$host$request_uri;
}

# --- HTTPS (puerto 443) ---
server {
    listen 443 ssl;
    server_name otra-empresa.com www.otra-empresa.com;

    # Certificado PROPIO de este dominio (generado por "generador-ssl-2")
    ssl_certificate     /etc/nginx/certs/otra-empresa/otra-empresa.com+1.pem;
    ssl_certificate_key /etc/nginx/certs/otra-empresa/otra-empresa.com+1-key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://module-portal:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
